### ISSUE TITLE
For corp members, show corp buy price?

### ISSUE THREAD

**Issue by nzifnab** [nzifnab/ali-website#10]
Right now buy prices are using the listed `ExternalSalePrice` from the market spreadsheet. We are capturing the `CorpMemberSalePrice` but not currently utilizing it.

A separate url could be used for corp members to give them the discounted prices? The order would need to get marked as a "Corp member" order, and when we go to fulfill that order we'd have to make sure an external person didn't use our corp-member link/pricing.

Do ranks come into play here at all or have we done away with that idea?

In an ideal world we'd use discord auth to make this determination. But that would require users to login using discord, and require a not-insignificant amount of working figuring out how discord authentication works & implementing it.

May require #12 

- [x] Temporary measure: token in the url to tell it to use the corp member buy price
- [x] Might need to put it into a cookie so that navigating around the site won't forget that you're a corp member.

**Comment by zuissak** [comment]
I think the only way to achieve this properly, is the long-way with Discord auth.. that way we can automatically present the correct price to users :/
