### ISSUE TITLE
Link production site to production spreadsheet

### ISSUE THREAD

**Issue by nzifnab** [nzifnab/ali-website#9]
Right now it's linking to an outdated spreadsheet. Needs to link to the production spreadsheet here:

https://docs.google.com/spreadsheets/d/1qpWUSwDnCoHWVNf4iJLbZ8EPMaqBMHdjdmHZeT5J5eY/edit#gid=0

- [x] Zifnab: (set the `MARKET_SHEET_ID` environment variable to the above)

- [x] Suissak:

1. The following email user needs READ access to the market spreadsheet: `ali-market-website@ascended-lunar-isle-website.iam.gserviceaccount.com`
    1. Click the "Share" button
    2. Enter above email address into "Add people and groups"
    3. Select them and select "Viewer" (doesn't need to be editor)
2. The following two named ranges need to be created on the spreadsheet:
    - `ItemNamesPublic` - needs to be set to `PurchasePricesPublic!B2:B`  (It'll automatically change it to the last row of `B` available)
    - `PurchaseWebsiteData` - needs to be set to `PurchasePricesPublic!A1:I`

    1. Go to "Data" menu => "Named Ranges".
    2. Type the name of the range and the range value, click "Done".

**Comment by zuissak** [comment]
1. Complete
2. Do you need me to do this? Unclear

**Comment by nzifnab** [comment]
@zuissak yes :) or give me edit access on the sheet and I can do it

**Comment by zuissak** [comment]
What's your gmail account ?
